Feature#4 form validations with yup
BC-MAY-21-RN/proyecto-proy-t01 pull request #16
Opened 2021-08-09 20:42 UTC by hancel-avila

# Description
 - We added Yup to build a LogIn and Signup schema for validation.
 - We used Formik to handle both validations that prints error messages in case a current input field is empty.
 - This will be helpful for future handle submissions and also a visual assistance for users when they missed to fill an input.

2021-08-09 20:45 UTC, cfcortes commented on src/constants/schemas/loginSchema.js
> +/* eslint-disable prettier/prettier */
Codacy has a fix for the issue: ['prettier/prettier' rule is disabled but never reported.](https://app.codacy.com/gh/BC-MAY-21-RN/proyecto-proy-t01/pullRequest?prid=7886201)
```suggestion

```

2021-08-09 20:45 UTC, cfcortes commented on src/constants/schemas/signupSchema.js
> +/* eslint-disable prettier/prettier */
Codacy has a fix for the issue: ['prettier/prettier' rule is disabled but never reported.](https://app.codacy.com/gh/BC-MAY-21-RN/proyecto-proy-t01/pullRequest?prid=7886201)
```suggestion

```

2021-08-10 00:17 UTC, YilKanda requested changes
When uploading your code to GitHub, remove the console.log(), as they should only function to test that the code is working while it is being done, but not leave them in the master branch.

2021-08-10 00:17 UTC, YilKanda commented on src/components/TextInput/index.js
> +  console.log(label);
Delete this console.log()

2021-08-10 00:17 UTC, YilKanda commented on src/components/TextInput/index.js
> +  console.log(props);
Delete this console.log()

2021-08-10 00:17 UTC, YilKanda commented on src/containers/SignUp/index.js
> +        onSubmit={values => console.log(values)}>
If the console.log() is not necessary, delete it.

2021-08-10 00:17 UTC, YilKanda commented on src/containers/Login/index.js
> +        onSubmit={values => console.log(values)}>
If the console.log() is not necessary, delete it.

2021-08-10 01:46 UTC, DemisRincon approved these changes

2021-08-10 14:12 UTC, yovanha approved these changes

2021-08-10 14:44 UTC, cfcortes approved these changes

2021-08-10 14:45 UTC, merged