Feature#8 Authentication with Email/Password added
BC-MAY-21-RN/proyecto-proy-t01 pull request #17
Opened 2021-08-10 18:31 UTC by yovanha

# Description
What did you implemented/Why did you implemented this:
 - We've implemented a signin method with email/password.
 - We've implement a function to detect if the email is already in use.
 - Once successfully the user is created the email is uploaded to Firebase.
 
  ## Screenshots 
![image](https://user-images.githubusercontent.com/72411097/128914676-2dc60122-3172-48d5-bb2d-5737ef457523.png)
![image](https://user-images.githubusercontent.com/72411097/128915153-99a8775e-b20e-4942-b8ea-10835d943539.png)

2021-08-10 19:38 UTC, OswaldoPineda submitted a review, later dismissed
very nice code!

2021-08-11 00:46 UTC, YilKanda requested changes

2021-08-11 15:00 UTC, yovanha commented on src/containers/SignUp/index.js
> +          agreeTerms: true,
Done

2021-08-11 15:00 UTC, yovanha commented on src/constants/schemas/validationSchema.js
> +      ' *Contraseña inválida',
Done

2021-08-11 15:00 UTC, yovanha commented on src/constants/schemas/validationSchema.js
> +    .oneOf([true], 'Aceptar los Terminos y Condiciones es requerido'),
Done

2021-08-11 15:00 UTC, yovanha commented on src/constants/schemas/validationSchema.js
> +    .min(8, ({min}) => ` *La contraseña debe tener minímo ${min} cáracteres`)
Done

2021-08-11 15:02 UTC, cortezroberto approved these changes
LGTM

2021-08-11 15:04 UTC, hancel-avila approved these changes
Nice work!

2021-08-11 15:05 UTC, merged