Fix Code Bugs
BC-MAY-21-RN/proyecto-proy-t01 pull request #49
Opened 2021-08-30 19:50 UTC by yovanha

# Description
We've added the correct font to the application.
We've fix the undefined value in the Additional Component function. Why? The code was not detecting the profilePic const to allow users to registred to the application.

2021-08-30 21:04 UTC, YilKanda requested changes
You added too many fonts. Are you going to occupy them all?

2021-08-30 21:04 UTC, YilKanda commented on ios/PetRescue/Info.plist
> +		<string>Poppins-Regular.ttf</string>
Check indentation

2021-08-31 01:05 UTC, DemisRincon approved these changes

2021-08-31 01:17 UTC, hancel-avila approved these changes
LGTM! 👍🏻

2021-08-31 01:20 UTC, merged